version: "3.8"

name: camagru

services:
  backend:

  db:
    ports:
      - 5432:5432
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    profiles:
      - development
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - camagru
